package com.kingfly.domain;

public class BaseConfiguration {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base_configuration.base_configuration_id
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private Integer baseConfigurationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base_configuration.base_configuration_prop
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String baseConfigurationProp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base_configuration.base_configuration_value
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String baseConfigurationValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base_configuration.base_configuration_description
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String baseConfigurationDescription;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base_configuration.base_configuration_id
	 * @return  the value of base_configuration.base_configuration_id
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public Integer getBaseConfigurationId() {
		return baseConfigurationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base_configuration.base_configuration_id
	 * @param baseConfigurationId  the value for base_configuration.base_configuration_id
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setBaseConfigurationId(Integer baseConfigurationId) {
		this.baseConfigurationId = baseConfigurationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base_configuration.base_configuration_prop
	 * @return  the value of base_configuration.base_configuration_prop
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getBaseConfigurationProp() {
		return baseConfigurationProp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base_configuration.base_configuration_prop
	 * @param baseConfigurationProp  the value for base_configuration.base_configuration_prop
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setBaseConfigurationProp(String baseConfigurationProp) {
		this.baseConfigurationProp = baseConfigurationProp == null ? null : baseConfigurationProp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base_configuration.base_configuration_value
	 * @return  the value of base_configuration.base_configuration_value
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getBaseConfigurationValue() {
		return baseConfigurationValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base_configuration.base_configuration_value
	 * @param baseConfigurationValue  the value for base_configuration.base_configuration_value
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setBaseConfigurationValue(String baseConfigurationValue) {
		this.baseConfigurationValue = baseConfigurationValue == null ? null : baseConfigurationValue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base_configuration.base_configuration_description
	 * @return  the value of base_configuration.base_configuration_description
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getBaseConfigurationDescription() {
		return baseConfigurationDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base_configuration.base_configuration_description
	 * @param baseConfigurationDescription  the value for base_configuration.base_configuration_description
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setBaseConfigurationDescription(String baseConfigurationDescription) {
		this.baseConfigurationDescription = baseConfigurationDescription == null ? null
				: baseConfigurationDescription.trim();
	}
}