package com.kingfly.domain;

public class Clearing {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column clearing.clearing_NO
	 * @mbg.generated  Sun Apr 08 21:08:47 CST 2018
	 */
	private String clearingNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column clearing.clearing _NO_description
	 * @mbg.generated  Sun Apr 08 21:08:47 CST 2018
	 */
	private String clearingNoDescription;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clearing.clearing_NO
	 * @return  the value of clearing.clearing_NO
	 * @mbg.generated  Sun Apr 08 21:08:47 CST 2018
	 */
	public String getClearingNo() {
		return clearingNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clearing.clearing_NO
	 * @param clearingNo  the value for clearing.clearing_NO
	 * @mbg.generated  Sun Apr 08 21:08:47 CST 2018
	 */
	public void setClearingNo(String clearingNo) {
		this.clearingNo = clearingNo == null ? null : clearingNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clearing.clearing _NO_description
	 * @return  the value of clearing.clearing _NO_description
	 * @mbg.generated  Sun Apr 08 21:08:47 CST 2018
	 */
	public String getClearingNoDescription() {
		return clearingNoDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clearing.clearing _NO_description
	 * @param clearingNoDescription  the value for clearing.clearing _NO_description
	 * @mbg.generated  Sun Apr 08 21:08:47 CST 2018
	 */
	public void setClearingNoDescription(String clearingNoDescription) {
		this.clearingNoDescription = clearingNoDescription == null ? null : clearingNoDescription.trim();
	}
}