package com.kingfly.domain;

public class CustTaskKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_task.cust_NO
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String custNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_task.true_file_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String trueFileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_task.cust_NO
     *
     * @return the value of cust_task.cust_NO
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_task.cust_NO
     *
     * @param custNo the value for cust_task.cust_NO
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_task.true_file_name
     *
     * @return the value of cust_task.true_file_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getTrueFileName() {
        return trueFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_task.true_file_name
     *
     * @param trueFileName the value for cust_task.true_file_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setTrueFileName(String trueFileName) {
        this.trueFileName = trueFileName == null ? null : trueFileName.trim();
    }
}