package com.kingfly.domain;

public class CustInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_info.cust_NO
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String custNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_info.sh_seat_NO
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String shSeatNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_info.settle _no
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String settleNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_info.szt_NO
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String sztNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_info.true_file_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String trueFileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_info.cust_NO
     *
     * @return the value of cust_info.cust_NO
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_info.cust_NO
     *
     * @param custNo the value for cust_info.cust_NO
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_info.sh_seat_NO
     *
     * @return the value of cust_info.sh_seat_NO
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getShSeatNo() {
        return shSeatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_info.sh_seat_NO
     *
     * @param shSeatNo the value for cust_info.sh_seat_NO
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setShSeatNo(String shSeatNo) {
        this.shSeatNo = shSeatNo == null ? null : shSeatNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_info.settle _no
     *
     * @return the value of cust_info.settle _no
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getSettleNo() {
        return settleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_info.settle _no
     *
     * @param settleNo the value for cust_info.settle _no
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setSettleNo(String settleNo) {
        this.settleNo = settleNo == null ? null : settleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_info.szt_NO
     *
     * @return the value of cust_info.szt_NO
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getSztNo() {
        return sztNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_info.szt_NO
     *
     * @param sztNo the value for cust_info.szt_NO
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setSztNo(String sztNo) {
        this.sztNo = sztNo == null ? null : sztNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_info.true_file_name
     *
     * @return the value of cust_info.true_file_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getTrueFileName() {
        return trueFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_info.true_file_name
     *
     * @param trueFileName the value for cust_info.true_file_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setTrueFileName(String trueFileName) {
        this.trueFileName = trueFileName == null ? null : trueFileName.trim();
    }
}