package com.kingfly.domain;

public class FileLocalChannel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file_local_channel.file_local_channel_id
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private Integer fileLocalChannelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file_local_channel.file_local_channel_path
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String fileLocalChannelPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file_local_channel.file_type
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String fileType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file_local_channel.file_local_channel_id
	 * @return  the value of file_local_channel.file_local_channel_id
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public Integer getFileLocalChannelId() {
		return fileLocalChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file_local_channel.file_local_channel_id
	 * @param fileLocalChannelId  the value for file_local_channel.file_local_channel_id
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setFileLocalChannelId(Integer fileLocalChannelId) {
		this.fileLocalChannelId = fileLocalChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file_local_channel.file_local_channel_path
	 * @return  the value of file_local_channel.file_local_channel_path
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getFileLocalChannelPath() {
		return fileLocalChannelPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file_local_channel.file_local_channel_path
	 * @param fileLocalChannelPath  the value for file_local_channel.file_local_channel_path
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setFileLocalChannelPath(String fileLocalChannelPath) {
		this.fileLocalChannelPath = fileLocalChannelPath == null ? null : fileLocalChannelPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file_local_channel.file_type
	 * @return  the value of file_local_channel.file_type
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getFileType() {
		return fileType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file_local_channel.file_type
	 * @param fileType  the value for file_local_channel.file_type
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setFileType(String fileType) {
		this.fileType = fileType == null ? null : fileType.trim();
	}
}