package com.kingfly.domain;

public class FileLocalChannel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_local_channel.file_local_channel_id
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String fileLocalChannelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_local_channel.file_local_channel_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String fileLocalChannelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_local_channel.file_local_channel_path
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String fileLocalChannelPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_local_channel.file_local_channel_id
     *
     * @return the value of file_local_channel.file_local_channel_id
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getFileLocalChannelId() {
        return fileLocalChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_local_channel.file_local_channel_id
     *
     * @param fileLocalChannelId the value for file_local_channel.file_local_channel_id
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setFileLocalChannelId(String fileLocalChannelId) {
        this.fileLocalChannelId = fileLocalChannelId == null ? null : fileLocalChannelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_local_channel.file_local_channel_name
     *
     * @return the value of file_local_channel.file_local_channel_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getFileLocalChannelName() {
        return fileLocalChannelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_local_channel.file_local_channel_name
     *
     * @param fileLocalChannelName the value for file_local_channel.file_local_channel_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setFileLocalChannelName(String fileLocalChannelName) {
        this.fileLocalChannelName = fileLocalChannelName == null ? null : fileLocalChannelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_local_channel.file_local_channel_path
     *
     * @return the value of file_local_channel.file_local_channel_path
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getFileLocalChannelPath() {
        return fileLocalChannelPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_local_channel.file_local_channel_path
     *
     * @param fileLocalChannelPath the value for file_local_channel.file_local_channel_path
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setFileLocalChannelPath(String fileLocalChannelPath) {
        this.fileLocalChannelPath = fileLocalChannelPath == null ? null : fileLocalChannelPath.trim();
    }
}