package com.kingfly.domain;

public class FileSourceChannel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_source_channel.file_source_channel_id
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String fileSourceChannelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_source_channel.file_source_channel_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String fileSourceChannelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_source_channel.file_source_channel_path
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String fileSourceChannelPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_source_channel.file_source_channel_id
     *
     * @return the value of file_source_channel.file_source_channel_id
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getFileSourceChannelId() {
        return fileSourceChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_source_channel.file_source_channel_id
     *
     * @param fileSourceChannelId the value for file_source_channel.file_source_channel_id
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setFileSourceChannelId(String fileSourceChannelId) {
        this.fileSourceChannelId = fileSourceChannelId == null ? null : fileSourceChannelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_source_channel.file_source_channel_name
     *
     * @return the value of file_source_channel.file_source_channel_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getFileSourceChannelName() {
        return fileSourceChannelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_source_channel.file_source_channel_name
     *
     * @param fileSourceChannelName the value for file_source_channel.file_source_channel_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setFileSourceChannelName(String fileSourceChannelName) {
        this.fileSourceChannelName = fileSourceChannelName == null ? null : fileSourceChannelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_source_channel.file_source_channel_path
     *
     * @return the value of file_source_channel.file_source_channel_path
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getFileSourceChannelPath() {
        return fileSourceChannelPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_source_channel.file_source_channel_path
     *
     * @param fileSourceChannelPath the value for file_source_channel.file_source_channel_path
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setFileSourceChannelPath(String fileSourceChannelPath) {
        this.fileSourceChannelPath = fileSourceChannelPath == null ? null : fileSourceChannelPath.trim();
    }
}