package com.kingfly.domain;

public class MarketFile {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column market_file.market_file_id
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	private Integer marketFileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column market_file.market_id
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	private String marketId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column market_file.file_type
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	private String fileType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column market_file.file_name
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	private String fileName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column market_file.market_file_id
	 * @return  the value of market_file.market_file_id
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	public Integer getMarketFileId() {
		return marketFileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column market_file.market_file_id
	 * @param marketFileId  the value for market_file.market_file_id
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	public void setMarketFileId(Integer marketFileId) {
		this.marketFileId = marketFileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column market_file.market_id
	 * @return  the value of market_file.market_id
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	public String getMarketId() {
		return marketId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column market_file.market_id
	 * @param marketId  the value for market_file.market_id
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	public void setMarketId(String marketId) {
		this.marketId = marketId == null ? null : marketId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column market_file.file_type
	 * @return  the value of market_file.file_type
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	public String getFileType() {
		return fileType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column market_file.file_type
	 * @param fileType  the value for market_file.file_type
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	public void setFileType(String fileType) {
		this.fileType = fileType == null ? null : fileType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column market_file.file_name
	 * @return  the value of market_file.file_name
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column market_file.file_name
	 * @param fileName  the value for market_file.file_name
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName == null ? null : fileName.trim();
	}
}