package com.kingfly.domain;

public class MarketFile extends MarketFileKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_file.file_type
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_file.file_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_file.file_type
     *
     * @return the value of market_file.file_type
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_file.file_type
     *
     * @param fileType the value for market_file.file_type
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_file.file_name
     *
     * @return the value of market_file.file_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_file.file_name
     *
     * @param fileName the value for market_file.file_name
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }
}