package com.kingfly.domain;

public class MarketFile extends MarketFileKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column market_file.file_type
	 * @mbg.generated  Sun Apr 08 15:58:13 CST 2018
	 */
	private String fileType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column market_file.file_prefix
	 * @mbg.generated  Sun Apr 08 15:58:13 CST 2018
	 */
	private String filePrefix;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column market_file.file_bz
	 * @mbg.generated  Sun Apr 08 15:58:13 CST 2018
	 */
	private String fileBz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column market_file.file_suffix
	 * @mbg.generated  Sun Apr 08 15:58:13 CST 2018
	 */
	private String fileSuffix;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column market_file.file_type
	 * @return  the value of market_file.file_type
	 * @mbg.generated  Sun Apr 08 15:58:13 CST 2018
	 */
	public String getFileType() {
		return fileType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column market_file.file_type
	 * @param fileType  the value for market_file.file_type
	 * @mbg.generated  Sun Apr 08 15:58:13 CST 2018
	 */
	public void setFileType(String fileType) {
		this.fileType = fileType == null ? null : fileType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column market_file.file_prefix
	 * @return  the value of market_file.file_prefix
	 * @mbg.generated  Sun Apr 08 15:58:13 CST 2018
	 */
	public String getFilePrefix() {
		return filePrefix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column market_file.file_prefix
	 * @param filePrefix  the value for market_file.file_prefix
	 * @mbg.generated  Sun Apr 08 15:58:13 CST 2018
	 */
	public void setFilePrefix(String filePrefix) {
		this.filePrefix = filePrefix == null ? null : filePrefix.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column market_file.file_bz
	 * @return  the value of market_file.file_bz
	 * @mbg.generated  Sun Apr 08 15:58:13 CST 2018
	 */
	public String getFileBz() {
		return fileBz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column market_file.file_bz
	 * @param fileBz  the value for market_file.file_bz
	 * @mbg.generated  Sun Apr 08 15:58:13 CST 2018
	 */
	public void setFileBz(String fileBz) {
		this.fileBz = fileBz == null ? null : fileBz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column market_file.file_suffix
	 * @return  the value of market_file.file_suffix
	 * @mbg.generated  Sun Apr 08 15:58:13 CST 2018
	 */
	public String getFileSuffix() {
		return fileSuffix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column market_file.file_suffix
	 * @param fileSuffix  the value for market_file.file_suffix
	 * @mbg.generated  Sun Apr 08 15:58:13 CST 2018
	 */
	public void setFileSuffix(String fileSuffix) {
		this.fileSuffix = fileSuffix == null ? null : fileSuffix.trim();
	}
}