package com.kingfly.domain;

public class PickupRule {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pickup_rule.pickup_rule_id
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private Integer pickupRuleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pickup_rule.market_file_id
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String marketFileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pickup_rule.pickup_rule_type
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String pickupRuleType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pickup_rule.pick_rule_desc
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String pickRuleDesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pickup_rule.pickup_rule_id
	 * @return  the value of pickup_rule.pickup_rule_id
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public Integer getPickupRuleId() {
		return pickupRuleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pickup_rule.pickup_rule_id
	 * @param pickupRuleId  the value for pickup_rule.pickup_rule_id
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setPickupRuleId(Integer pickupRuleId) {
		this.pickupRuleId = pickupRuleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pickup_rule.market_file_id
	 * @return  the value of pickup_rule.market_file_id
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getMarketFileId() {
		return marketFileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pickup_rule.market_file_id
	 * @param marketFileId  the value for pickup_rule.market_file_id
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setMarketFileId(String marketFileId) {
		this.marketFileId = marketFileId == null ? null : marketFileId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pickup_rule.pickup_rule_type
	 * @return  the value of pickup_rule.pickup_rule_type
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getPickupRuleType() {
		return pickupRuleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pickup_rule.pickup_rule_type
	 * @param pickupRuleType  the value for pickup_rule.pickup_rule_type
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setPickupRuleType(String pickupRuleType) {
		this.pickupRuleType = pickupRuleType == null ? null : pickupRuleType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pickup_rule.pick_rule_desc
	 * @return  the value of pickup_rule.pick_rule_desc
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getPickRuleDesc() {
		return pickRuleDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pickup_rule.pick_rule_desc
	 * @param pickRuleDesc  the value for pickup_rule.pick_rule_desc
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setPickRuleDesc(String pickRuleDesc) {
		this.pickRuleDesc = pickRuleDesc == null ? null : pickRuleDesc.trim();
	}
}