package com.kingfly.domain;

public class Settle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle.settle _no
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String settleNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle.settle_NO_description
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    private String settleNoDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle.settle _no
     *
     * @return the value of settle.settle _no
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getSettleNo() {
        return settleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle.settle _no
     *
     * @param settleNo the value for settle.settle _no
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setSettleNo(String settleNo) {
        this.settleNo = settleNo == null ? null : settleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle.settle_NO_description
     *
     * @return the value of settle.settle_NO_description
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public String getSettleNoDescription() {
        return settleNoDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle.settle_NO_description
     *
     * @param settleNoDescription the value for settle.settle_NO_description
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    public void setSettleNoDescription(String settleNoDescription) {
        this.settleNoDescription = settleNoDescription == null ? null : settleNoDescription.trim();
    }
}