package com.kingfly.domain;

public class Shseat {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sh_seat.sh_seat_NO
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String shSeatNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sh_seat.seat_description
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String seatDescription;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sh_seat.sh_seat_NO
	 * @return  the value of sh_seat.sh_seat_NO
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getShSeatNo() {
		return shSeatNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sh_seat.sh_seat_NO
	 * @param shSeatNo  the value for sh_seat.sh_seat_NO
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setShSeatNo(String shSeatNo) {
		this.shSeatNo = shSeatNo == null ? null : shSeatNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sh_seat.seat_description
	 * @return  the value of sh_seat.seat_description
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getSeatDescription() {
		return seatDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sh_seat.seat_description
	 * @param seatDescription  the value for sh_seat.seat_description
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setSeatDescription(String seatDescription) {
		this.seatDescription = seatDescription == null ? null : seatDescription.trim();
	}
}