package com.kingfly.domain;

public class Szt {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column szt.szt_NO
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String sztNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column szt.szt_path
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String sztPath;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column szt.szt_NO
	 * @return  the value of szt.szt_NO
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getSztNo() {
		return sztNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column szt.szt_NO
	 * @param sztNo  the value for szt.szt_NO
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setSztNo(String sztNo) {
		this.sztNo = sztNo == null ? null : sztNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column szt.szt_path
	 * @return  the value of szt.szt_path
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getSztPath() {
		return sztPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column szt.szt_path
	 * @param sztPath  the value for szt.szt_path
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setSztPath(String sztPath) {
		this.sztPath = sztPath == null ? null : sztPath.trim();
	}
}