package com.kingfly.domain;

public class Task extends TaskKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.true_file_name
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String trueFileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.task_status
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String taskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.task_desc
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	private String taskDesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.true_file_name
	 * @return  the value of task.true_file_name
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getTrueFileName() {
		return trueFileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.true_file_name
	 * @param trueFileName  the value for task.true_file_name
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setTrueFileName(String trueFileName) {
		this.trueFileName = trueFileName == null ? null : trueFileName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.task_status
	 * @return  the value of task.task_status
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getTaskStatus() {
		return taskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.task_status
	 * @param taskStatus  the value for task.task_status
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setTaskStatus(String taskStatus) {
		this.taskStatus = taskStatus == null ? null : taskStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.task_desc
	 * @return  the value of task.task_desc
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public String getTaskDesc() {
		return taskDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.task_desc
	 * @param taskDesc  the value for task.task_desc
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	public void setTaskDesc(String taskDesc) {
		this.taskDesc = taskDesc == null ? null : taskDesc.trim();
	}
}