package com.kingfly.IDao;

import com.kingfly.domain.BaseConfiguration;

public interface BaseConfigurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_configuration
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int deleteByPrimaryKey(Integer baseConfigurationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_configuration
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insert(BaseConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_configuration
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insertSelective(BaseConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_configuration
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    BaseConfiguration selectByPrimaryKey(Integer baseConfigurationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_configuration
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int updateByPrimaryKeySelective(BaseConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_configuration
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int updateByPrimaryKey(BaseConfiguration record);
}