package com.kingfly.IDao;

import com.kingfly.domain.Clearing;

public interface ClearingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clearing
	 * @mbg.generated  Sun Apr 08 21:08:47 CST 2018
	 */
	int deleteByPrimaryKey(String clearingNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clearing
	 * @mbg.generated  Sun Apr 08 21:08:47 CST 2018
	 */
	int insert(Clearing record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clearing
	 * @mbg.generated  Sun Apr 08 21:08:47 CST 2018
	 */
	int insertSelective(Clearing record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clearing
	 * @mbg.generated  Sun Apr 08 21:08:47 CST 2018
	 */
	Clearing selectByPrimaryKey(String clearingNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clearing
	 * @mbg.generated  Sun Apr 08 21:08:47 CST 2018
	 */
	int updateByPrimaryKeySelective(Clearing record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clearing
	 * @mbg.generated  Sun Apr 08 21:08:47 CST 2018
	 */
	int updateByPrimaryKey(Clearing record);
}