package com.kingfly.IDao;

import com.kingfly.domain.CustTaskKey;

public interface CustTaskMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust_task
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int deleteByPrimaryKey(CustTaskKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust_task
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int insert(CustTaskKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cust_task
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int insertSelective(CustTaskKey record);
}