package com.kingfly.IDao;

import com.kingfly.domain.CustTaskKey;

public interface CustTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_task
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int deleteByPrimaryKey(CustTaskKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_task
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insert(CustTaskKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_task
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insertSelective(CustTaskKey record);
}