package com.kingfly.IDao;

import com.kingfly.domain.FileLocalChannel;

public interface FileLocalChannelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_local_channel
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int deleteByPrimaryKey(Integer fileLocalChannelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_local_channel
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int insert(FileLocalChannel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_local_channel
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int insertSelective(FileLocalChannel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_local_channel
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	FileLocalChannel selectByPrimaryKey(Integer fileLocalChannelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_local_channel
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int updateByPrimaryKeySelective(FileLocalChannel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_local_channel
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int updateByPrimaryKey(FileLocalChannel record);
}