package com.kingfly.IDao;

import com.kingfly.domain.FileLocalChannel;

public interface FileLocalChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_local_channel
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int deleteByPrimaryKey(String fileLocalChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_local_channel
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insert(FileLocalChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_local_channel
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insertSelective(FileLocalChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_local_channel
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    FileLocalChannel selectByPrimaryKey(String fileLocalChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_local_channel
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int updateByPrimaryKeySelective(FileLocalChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_local_channel
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int updateByPrimaryKey(FileLocalChannel record);
}