package com.kingfly.IDao;

import com.kingfly.domain.FileSourceChannel;

public interface FileSourceChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_source_channel
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int deleteByPrimaryKey(String fileSourceChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_source_channel
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insert(FileSourceChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_source_channel
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insertSelective(FileSourceChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_source_channel
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    FileSourceChannel selectByPrimaryKey(String fileSourceChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_source_channel
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int updateByPrimaryKeySelective(FileSourceChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_source_channel
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int updateByPrimaryKey(FileSourceChannel record);
}