package com.kingfly.IDao;

import com.kingfly.domain.MarketFile;
import com.kingfly.domain.MarketFileKey;

public interface MarketFileMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table market_file
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	int insert(MarketFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table market_file
	 * @mbg.generated  Wed Apr 18 21:12:25 CST 2018
	 */
	int insertSelective(MarketFile record);
}