package com.kingfly.IDao;

import com.kingfly.domain.PickupRule;

public interface PickupRuleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pickup_rule
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int deleteByPrimaryKey(Integer pickupRuleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pickup_rule
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int insert(PickupRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pickup_rule
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int insertSelective(PickupRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pickup_rule
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	PickupRule selectByPrimaryKey(Integer pickupRuleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pickup_rule
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int updateByPrimaryKeySelective(PickupRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pickup_rule
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int updateByPrimaryKey(PickupRule record);
}