package com.kingfly.IDao;

import com.kingfly.domain.Settle;

public interface SettleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int deleteByPrimaryKey(String settleNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insert(Settle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insertSelective(Settle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    Settle selectByPrimaryKey(String settleNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int updateByPrimaryKeySelective(Settle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int updateByPrimaryKey(Settle record);
}