package com.kingfly.IDao;

import com.kingfly.domain.Settle;

public interface SettleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settle
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int deleteByPrimaryKey(String settleNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settle
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int insert(Settle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settle
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int insertSelective(Settle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settle
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	Settle selectByPrimaryKey(String settleNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settle
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int updateByPrimaryKeySelective(Settle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table settle
	 * @mbg.generated  Fri Apr 06 23:24:27 CST 2018
	 */
	int updateByPrimaryKey(Settle record);
}