package com.kingfly.IDao;

import com.kingfly.domain.Szt;

public interface SztMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table szt
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int deleteByPrimaryKey(String sztNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table szt
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insert(Szt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table szt
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insertSelective(Szt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table szt
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    Szt selectByPrimaryKey(String sztNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table szt
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int updateByPrimaryKeySelective(Szt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table szt
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int updateByPrimaryKey(Szt record);
}