package com.kingfly.IDao;

import com.kingfly.domain.Task;
import com.kingfly.domain.TaskKey;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int deleteByPrimaryKey(TaskKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    Task selectByPrimaryKey(TaskKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Sun Apr 01 14:50:31 CST 2018
     */
    int updateByPrimaryKey(Task record);
}